-- MySQL Script generated by MySQL Workbench
-- Sun Apr  4 19:06:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`vaccine center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccine center` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `vaccine center_id` INT NULL COMMENT 'if NULL, hospital isn\'t a vaccination center.',
  PRIMARY KEY (`id`),
  INDEX `fk_hospital_vaccine center1_idx` (`vaccine center_id` ASC) VISIBLE,
  CONSTRAINT `fk_hospital_vaccine center1`
    FOREIGN KEY (`vaccine center_id`)
    REFERENCES `mydb`.`vaccine center` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HDIKA_person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HDIKA_person` (
  `AMKA` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `age` INT NOT NULL,
  `date_of_birth` DATE NOT NULL,
  PRIMARY KEY (`AMKA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `background` VARCHAR(45) NULL,
  `AMKA` INT NOT NULL,
  `contact_AMKA` INT NOT NULL,
  `hospital_id` INT NOT NULL,
  PRIMARY KEY (`AMKA`, `hospital_id`),
  INDEX `fk_patient_HDIKA_person1_idx` (`AMKA` ASC) VISIBLE,
  INDEX `fk_patient_patient1_idx` (`contact_AMKA` ASC) VISIBLE,
  INDEX `fk_patient_hospital1_idx` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `fk_patient_HDIKA_person1`
    FOREIGN KEY (`AMKA`)
    REFERENCES `mydb`.`HDIKA_person` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_patient1`
    FOREIGN KEY (`contact_AMKA`)
    REFERENCES `mydb`.`patient` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_hospital1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mydb`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `speciality` VARCHAR(45) NOT NULL,
  `hospital_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doctor_hospital1_idx` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_hospital1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mydb`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ward` (
  `id` INT NOT NULL,
  `bed_count` INT NOT NULL,
  `patient_count` INT NOT NULL,
  `hospital_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ward_hospital1_idx` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `fk_ward_hospital1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mydb`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`room` (
  `id` INT NOT NULL,
  `bed_count` INT NOT NULL,
  `ward_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_room_ward1_idx` (`ward_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_ward1`
    FOREIGN KEY (`ward_id`)
    REFERENCES `mydb`.`ward` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`diagnostic_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`diagnostic_center` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `vaccine center_id` INT NULL COMMENT 'if NULL, diagnostic center isn\'t a vaccination center.',
  PRIMARY KEY (`id`),
  INDEX `fk_diagnostic_center_vaccine center1_idx` (`vaccine center_id` ASC) VISIBLE,
  CONSTRAINT `fk_diagnostic_center_vaccine center1`
    FOREIGN KEY (`vaccine center_id`)
    REFERENCES `mydb`.`vaccine center` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EODY_covid_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EODY_covid_test` (
  `type` VARCHAR(45) NOT NULL,
  `result` ENUM('POSITIVE', 'NEGATIVE') NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital_visit` (
  `date` DATE NOT NULL,
  `doctor_id` INT NOT NULL,
  `EODY_covid_test_id` INT NOT NULL,
  `hospital_id` INT NOT NULL,
  `patient_AMKA` INT NOT NULL,
  PRIMARY KEY (`date`, `hospital_id`, `patient_AMKA`),
  INDEX `fk_visit_doctor1_idx` (`doctor_id` ASC) VISIBLE,
  INDEX `fk_hospital_visit_EODY_covid_test1_idx` (`EODY_covid_test_id` ASC) VISIBLE,
  INDEX `fk_hospital_visit_hospital1_idx` (`hospital_id` ASC) VISIBLE,
  INDEX `fk_hospital_visit_patient1_idx` (`patient_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_visit_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospital_visit_EODY_covid_test1`
    FOREIGN KEY (`EODY_covid_test_id`)
    REFERENCES `mydb`.`EODY_covid_test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospital_visit_hospital1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `mydb`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospital_visit_patient1`
    FOREIGN KEY (`patient_AMKA`)
    REFERENCES `mydb`.`patient` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`simple_ward`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`simple_ward` (
  `type` ENUM('NO_COVID', 'COVID') NOT NULL,
  `speciality` VARCHAR(45) NOT NULL,
  `ward_id` INT NOT NULL,
  PRIMARY KEY (`ward_id`),
  CONSTRAINT `fk_simple_ward_ward1`
    FOREIGN KEY (`ward_id`)
    REFERENCES `mydb`.`ward` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ICU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ICU` (
  `ward_id` INT NOT NULL,
  PRIMARY KEY (`ward_id`),
  CONSTRAINT `fk_ICU_ward1`
    FOREIGN KEY (`ward_id`)
    REFERENCES `mydb`.`ward` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shift` (
  `doctor_id` INT NOT NULL,
  `ward_id` INT NOT NULL,
  `day` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`doctor_id`, `ward_id`, `day`),
  INDEX `fk_doctor_has_ward_ward1_idx` (`ward_id` ASC) VISIBLE,
  INDEX `fk_doctor_has_ward_doctor1_idx` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_doctor_has_ward_doctor1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `mydb`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doctor_has_ward_ward1`
    FOREIGN KEY (`ward_id`)
    REFERENCES `mydb`.`ward` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`da_center_visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`da_center_visit` (
  `date` DATE NOT NULL COMMENT 'lets gooo\n',
  `EODY_covid_test_id` INT NOT NULL,
  `HDIKA_person_AMKA` INT NOT NULL,
  `diagnostic_center_id` INT NOT NULL,
  PRIMARY KEY (`date`, `HDIKA_person_AMKA`, `diagnostic_center_id`),
  INDEX `fk_da_center_visit_EODY_covid_test1_idx` (`EODY_covid_test_id` ASC) VISIBLE,
  INDEX `fk_da_center_visit_HDIKA_person1_idx` (`HDIKA_person_AMKA` ASC) VISIBLE,
  INDEX `fk_da_center_visit_diagnostic_center1_idx` (`diagnostic_center_id` ASC) VISIBLE,
  CONSTRAINT `fk_da_center_visit_EODY_covid_test1`
    FOREIGN KEY (`EODY_covid_test_id`)
    REFERENCES `mydb`.`EODY_covid_test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_da_center_visit_HDIKA_person1`
    FOREIGN KEY (`HDIKA_person_AMKA`)
    REFERENCES `mydb`.`HDIKA_person` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_da_center_visit_diagnostic_center1`
    FOREIGN KEY (`diagnostic_center_id`)
    REFERENCES `mydb`.`diagnostic_center` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospitalization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospitalization` (
  `symptoms` VARCHAR(45) NOT NULL,
  `medication` VARCHAR(45) NOT NULL,
  `room_id` INT NOT NULL,
  `hospital_visit_date` DATE NOT NULL,
  `hospital_visit_patient_AMKA` INT NOT NULL,
  INDEX `fk_hospitalization_room1_idx` (`room_id` ASC) VISIBLE,
  PRIMARY KEY (`hospital_visit_date`, `hospital_visit_patient_AMKA`),
  CONSTRAINT `fk_hospitalization_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `mydb`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hospitalization_hospital_visit1`
    FOREIGN KEY (`hospital_visit_date`)
    REFERENCES `mydb`.`hospital_visit` (`date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccine_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccine_company` (
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `technology` VARCHAR(45) NOT NULL,
  `storing_conditions` VARCHAR(45) NOT NULL,
  `monthly_production` INT NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccine` (
  `name` VARCHAR(45) NOT NULL,
  `dose` INT NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`storing_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`storing_company` (
  `id` INT NOT NULL,
  `vaccine_company_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_storing_company_vaccine_company1_idx` (`vaccine_company_name` ASC) VISIBLE,
  CONSTRAINT `fk_storing_company_vaccine_company1`
    FOREIGN KEY (`vaccine_company_name`)
    REFERENCES `mydb`.`vaccine_company` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccine_shipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccine_shipment` (
  `id` INT NOT NULL,
  `production_date` DATE NOT NULL,
  `amount` INT NOT NULL,
  `destination_country` VARCHAR(45) NOT NULL,
  `vaccine_name` VARCHAR(45) NOT NULL,
  `storing_company_id` INT NOT NULL,
  `vaccine center_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vaccine_shipment_vaccine1_idx` (`vaccine_name` ASC) VISIBLE,
  INDEX `fk_vaccine_shipment_storing_company1_idx` (`storing_company_id` ASC) VISIBLE,
  INDEX `fk_vaccine_shipment_vaccine center1_idx` (`vaccine center_id` ASC) VISIBLE,
  CONSTRAINT `fk_vaccine_shipment_vaccine1`
    FOREIGN KEY (`vaccine_name`)
    REFERENCES `mydb`.`vaccine` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vaccine_shipment_storing_company1`
    FOREIGN KEY (`storing_company_id`)
    REFERENCES `mydb`.`storing_company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vaccine_shipment_vaccine center1`
    FOREIGN KEY (`vaccine center_id`)
    REFERENCES `mydb`.`vaccine center` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`approved_vaccine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`approved_vaccine` (
  `EMA_code` INT NOT NULL,
  `vaccine_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vaccine_name`),
  CONSTRAINT `fk_approved_vaccine_vaccine1`
    FOREIGN KEY (`vaccine_name`)
    REFERENCES `mydb`.`vaccine` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`not_yet_approved_vaccine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`not_yet_approved_vaccine` (
  `possible_approval_date` DATE NOT NULL,
  `vaccine_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vaccine_name`),
  CONSTRAINT `fk_non_approved_vaccine_vaccine1`
    FOREIGN KEY (`vaccine_name`)
    REFERENCES `mydb`.`vaccine` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccine_company_has_vaccine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccine_company_has_vaccine` (
  `vaccine_company_name` VARCHAR(45) NOT NULL,
  `vaccine_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`vaccine_company_name`, `vaccine_name`),
  INDEX `fk_vaccine_company_has_vaccine_vaccine1_idx` (`vaccine_name` ASC) VISIBLE,
  INDEX `fk_vaccine_company_has_vaccine_vaccine_company1_idx` (`vaccine_company_name` ASC) VISIBLE,
  CONSTRAINT `fk_vaccine_company_has_vaccine_vaccine_company1`
    FOREIGN KEY (`vaccine_company_name`)
    REFERENCES `mydb`.`vaccine_company` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vaccine_company_has_vaccine_vaccine1`
    FOREIGN KEY (`vaccine_name`)
    REFERENCES `mydb`.`vaccine` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vaccine_dose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vaccine_dose` (
  `vaccine center_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `HDIKA_person_AMKA` INT NOT NULL,
  PRIMARY KEY (`vaccine center_id`, `date`, `HDIKA_person_AMKA`),
  INDEX `fk_vaccine center_has_person_vaccine center1_idx` (`vaccine center_id` ASC) VISIBLE,
  INDEX `fk_vaccine_dose_HDIKA_person1_idx` (`HDIKA_person_AMKA` ASC) VISIBLE,
  CONSTRAINT `fk_vaccine center_has_person_vaccine center1`
    FOREIGN KEY (`vaccine center_id`)
    REFERENCES `mydb`.`vaccine center` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vaccine_dose_HDIKA_person1`
    FOREIGN KEY (`HDIKA_person_AMKA`)
    REFERENCES `mydb`.`HDIKA_person` (`AMKA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
